ALTER TYPE "WarehouseMovementType" ADD VALUE IF NOT EXISTS 'MANUAL_RECEIPT';
ALTER TYPE "WarehouseMovementType" ADD VALUE IF NOT EXISTS 'MANUAL_DISPATCH';
ALTER TYPE "WarehouseMovementType" ADD VALUE IF NOT EXISTS 'STOCK_COUNT';
ALTER TYPE "WarehouseMovementType" ADD VALUE IF NOT EXISTS 'DISPATCH';
